version: '3.8'

services:
  web:
    build: .
    ports:
      - "5050:5050"  # Exposes port 5050 on host and container
    environment:
      - FLASK_ENV=development  # Sets Flask environment to development
    volumes:
      - . :/app  # Mounts host directory to container directory
